#!/bin/sh
UNAME="`uname -a`"
/bin/echo "<div id=si_uname>$UNAME</div>" > /var/lib/asterisk/static-http/config/bkps/sysinfo_output.html
                
UPTIME="`uptime`"
/bin/echo "<div id=si_uptime>$UPTIME</div>" >> /var/lib/asterisk/static-http/config/bkps/sysinfo_output.html
                  
ASTERISK="`/usr/sbin/asterisk -V`"
/bin/echo "<div id=si_astver>$ASTERISK</div>" >> /var/lib/asterisk/static-http/config/bkps/sysinfo_output.html
                
TODAY="`date`"
/bin/echo "<div id=si_date>$TODAY</div>" >> /var/lib/asterisk/static-http/config/bkps/sysinfo_output.html

HOSTNAME="`hostname -f`"
/bin/echo "<div id=si_hostname>$HOSTNAME</div>" >> /var/lib/asterisk/static-http/config/bkps/sysinfo_output.html
     
IFCONFIG=`ifconfig`
/bin/echo "<div id=si_ifconfig>$IFCONFIG</div>" >> /var/lib/asterisk/static-http/config/bkps/sysinfo_output.html
                         
DISKUSAGE=`df -h`
/bin/echo "<div id=si_du>$DISKUSAGE</div>" >> /var/lib/asterisk/static-http/config/bkps/sysinfo_output.html
                        
MEMORYUSAGE=`free`
/bin/echo "<div id=si_free>$MEMORYUSAGE</div>" >> /var/lib/asterisk/static-http/config/bkps/sysinfo_output.html


THISMONTH=`/bin/date +%b`
THISDAY=`/bin/date +%d`
THIS_DAY=`/bin/date +%_d`
/bin/grep /var/log/asterisk/messages -e "$THISMONTH\( $THISDAY\| $THIS_DAY\)" > /var/lib/asterisk/static-http/config/bkps/today_log.html
